package com.cloud.app.model;

import java.util.Date;

public class Friend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRIEND_TABLE.FRIENDS_ID
     *
     * @mbggenerated
     */
    private Integer friendsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRIEND_TABLE.FRIEND_A
     *
     * @mbggenerated
     */
    private Integer friendA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRIEND_TABLE.FRIEND_B
     *
     * @mbggenerated
     */
    private Integer friendB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRIEND_TABLE.TIME_BUILD
     *
     * @mbggenerated
     */
    private Date timeBuild;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRIEND_TABLE.COMMENT
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRIEND_TABLE.FRIENDS_ID
     *
     * @return the value of FRIEND_TABLE.FRIENDS_ID
     *
     * @mbggenerated
     */
    public Integer getFriendsId() {
        return friendsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRIEND_TABLE.FRIENDS_ID
     *
     * @param friendsId the value for FRIEND_TABLE.FRIENDS_ID
     *
     * @mbggenerated
     */
    public void setFriendsId(Integer friendsId) {
        this.friendsId = friendsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRIEND_TABLE.FRIEND_A
     *
     * @return the value of FRIEND_TABLE.FRIEND_A
     *
     * @mbggenerated
     */
    public Integer getFriendA() {
        return friendA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRIEND_TABLE.FRIEND_A
     *
     * @param friendA the value for FRIEND_TABLE.FRIEND_A
     *
     * @mbggenerated
     */
    public void setFriendA(Integer friendA) {
        this.friendA = friendA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRIEND_TABLE.FRIEND_B
     *
     * @return the value of FRIEND_TABLE.FRIEND_B
     *
     * @mbggenerated
     */
    public Integer getFriendB() {
        return friendB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRIEND_TABLE.FRIEND_B
     *
     * @param friendB the value for FRIEND_TABLE.FRIEND_B
     *
     * @mbggenerated
     */
    public void setFriendB(Integer friendB) {
        this.friendB = friendB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRIEND_TABLE.TIME_BUILD
     *
     * @return the value of FRIEND_TABLE.TIME_BUILD
     *
     * @mbggenerated
     */
    public Date getTimeBuild() {
        return timeBuild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRIEND_TABLE.TIME_BUILD
     *
     * @param timeBuild the value for FRIEND_TABLE.TIME_BUILD
     *
     * @mbggenerated
     */
    public void setTimeBuild(Date timeBuild) {
        this.timeBuild = timeBuild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRIEND_TABLE.COMMENT
     *
     * @return the value of FRIEND_TABLE.COMMENT
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRIEND_TABLE.COMMENT
     *
     * @param comment the value for FRIEND_TABLE.COMMENT
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}