package com.cloud.app.model;

import java.util.Date;

import org.springframework.stereotype.Repository;
@Repository
public class GroupFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GROUP_FILE.UPLOAD_ID
     *
     * @mbggenerated
     */
    private Integer uploadId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GROUP_FILE.GROUP_ID
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GROUP_FILE.FILE_NAME
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GROUP_FILE.FILE_ID
     *
     * @mbggenerated
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GROUP_FILE.UPLOADER_ID
     *
     * @mbggenerated
     */
    private Integer uploaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GROUP_FILE.UPLOAD_TIME
     *
     * @mbggenerated
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GROUP_FILE.STATE
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GROUP_FILE.DELETE_TIME
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GROUP_FILE.COMMENT
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GROUP_FILE.UPLOAD_ID
     *
     * @return the value of GROUP_FILE.UPLOAD_ID
     *
     * @mbggenerated
     */
    public Integer getUploadId() {
        return uploadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GROUP_FILE.UPLOAD_ID
     *
     * @param uploadId the value for GROUP_FILE.UPLOAD_ID
     *
     * @mbggenerated
     */
    public void setUploadId(Integer uploadId) {
        this.uploadId = uploadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GROUP_FILE.GROUP_ID
     *
     * @return the value of GROUP_FILE.GROUP_ID
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GROUP_FILE.GROUP_ID
     *
     * @param groupId the value for GROUP_FILE.GROUP_ID
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GROUP_FILE.FILE_NAME
     *
     * @return the value of GROUP_FILE.FILE_NAME
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GROUP_FILE.FILE_NAME
     *
     * @param fileName the value for GROUP_FILE.FILE_NAME
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GROUP_FILE.FILE_ID
     *
     * @return the value of GROUP_FILE.FILE_ID
     *
     * @mbggenerated
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GROUP_FILE.FILE_ID
     *
     * @param fileId the value for GROUP_FILE.FILE_ID
     *
     * @mbggenerated
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GROUP_FILE.UPLOADER_ID
     *
     * @return the value of GROUP_FILE.UPLOADER_ID
     *
     * @mbggenerated
     */
    public Integer getUploaderId() {
        return uploaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GROUP_FILE.UPLOADER_ID
     *
     * @param uploaderId the value for GROUP_FILE.UPLOADER_ID
     *
     * @mbggenerated
     */
    public void setUploaderId(Integer uploaderId) {
        this.uploaderId = uploaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GROUP_FILE.UPLOAD_TIME
     *
     * @return the value of GROUP_FILE.UPLOAD_TIME
     *
     * @mbggenerated
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GROUP_FILE.UPLOAD_TIME
     *
     * @param uploadTime the value for GROUP_FILE.UPLOAD_TIME
     *
     * @mbggenerated
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GROUP_FILE.STATE
     *
     * @return the value of GROUP_FILE.STATE
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GROUP_FILE.STATE
     *
     * @param state the value for GROUP_FILE.STATE
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GROUP_FILE.DELETE_TIME
     *
     * @return the value of GROUP_FILE.DELETE_TIME
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GROUP_FILE.DELETE_TIME
     *
     * @param deleteTime the value for GROUP_FILE.DELETE_TIME
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GROUP_FILE.COMMENT
     *
     * @return the value of GROUP_FILE.COMMENT
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GROUP_FILE.COMMENT
     *
     * @param comment the value for GROUP_FILE.COMMENT
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}