package com.cloud.app.model;

import java.util.Date;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_TABLE.MEMBERS_ID
     *
     * @mbggenerated
     */
    private Integer membersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_TABLE.GROUP_ID
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_TABLE.MEMBER_ID
     *
     * @mbggenerated
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_TABLE.TIME_BUILD
     *
     * @mbggenerated
     */
    private Date timeBuild;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_TABLE.COMMENT
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_TABLE.MEMBERS_ID
     *
     * @return the value of MEMBER_TABLE.MEMBERS_ID
     *
     * @mbggenerated
     */
    public Integer getMembersId() {
        return membersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_TABLE.MEMBERS_ID
     *
     * @param membersId the value for MEMBER_TABLE.MEMBERS_ID
     *
     * @mbggenerated
     */
    public void setMembersId(Integer membersId) {
        this.membersId = membersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_TABLE.GROUP_ID
     *
     * @return the value of MEMBER_TABLE.GROUP_ID
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_TABLE.GROUP_ID
     *
     * @param groupId the value for MEMBER_TABLE.GROUP_ID
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_TABLE.MEMBER_ID
     *
     * @return the value of MEMBER_TABLE.MEMBER_ID
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_TABLE.MEMBER_ID
     *
     * @param memberId the value for MEMBER_TABLE.MEMBER_ID
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_TABLE.TIME_BUILD
     *
     * @return the value of MEMBER_TABLE.TIME_BUILD
     *
     * @mbggenerated
     */
    public Date getTimeBuild() {
        return timeBuild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_TABLE.TIME_BUILD
     *
     * @param timeBuild the value for MEMBER_TABLE.TIME_BUILD
     *
     * @mbggenerated
     */
    public void setTimeBuild(Date timeBuild) {
        this.timeBuild = timeBuild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_TABLE.COMMENT
     *
     * @return the value of MEMBER_TABLE.COMMENT
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_TABLE.COMMENT
     *
     * @param comment the value for MEMBER_TABLE.COMMENT
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}