package com.cloud.app.model;

import java.util.Date;

import org.springframework.stereotype.Repository;
@Repository
public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE_TABLE.MESSAGE_ID
     *
     * @mbggenerated
     */
    private Integer messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE_TABLE.FROM_ID
     *
     * @mbggenerated
     */
    private Integer fromId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE_TABLE.TO_ID
     *
     * @mbggenerated
     */
    private Integer toId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE_TABLE.MESSAGE_TYPE
     *
     * @mbggenerated
     */
    private Integer messageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE_TABLE.MESSAGE_CONTENT
     *
     * @mbggenerated
     */
    private String messageContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE_TABLE.STATE_OP
     *
     * @mbggenerated
     */
    private Integer stateOp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE_TABLE.TIME_BUILD
     *
     * @mbggenerated
     */
    private Date timeBuild;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE_TABLE.COMMENT
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE_TABLE.MESSAGE_ID
     *
     * @return the value of MESSAGE_TABLE.MESSAGE_ID
     *
     * @mbggenerated
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE_TABLE.MESSAGE_ID
     *
     * @param messageId the value for MESSAGE_TABLE.MESSAGE_ID
     *
     * @mbggenerated
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE_TABLE.FROM_ID
     *
     * @return the value of MESSAGE_TABLE.FROM_ID
     *
     * @mbggenerated
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE_TABLE.FROM_ID
     *
     * @param fromId the value for MESSAGE_TABLE.FROM_ID
     *
     * @mbggenerated
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE_TABLE.TO_ID
     *
     * @return the value of MESSAGE_TABLE.TO_ID
     *
     * @mbggenerated
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE_TABLE.TO_ID
     *
     * @param toId the value for MESSAGE_TABLE.TO_ID
     *
     * @mbggenerated
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE_TABLE.MESSAGE_TYPE
     *
     * @return the value of MESSAGE_TABLE.MESSAGE_TYPE
     *
     * @mbggenerated
     */
    public Integer getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE_TABLE.MESSAGE_TYPE
     *
     * @param messageType the value for MESSAGE_TABLE.MESSAGE_TYPE
     *
     * @mbggenerated
     */
    public void setMessageType(Integer messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE_TABLE.MESSAGE_CONTENT
     *
     * @return the value of MESSAGE_TABLE.MESSAGE_CONTENT
     *
     * @mbggenerated
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE_TABLE.MESSAGE_CONTENT
     *
     * @param messageContent the value for MESSAGE_TABLE.MESSAGE_CONTENT
     *
     * @mbggenerated
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent == null ? null : messageContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE_TABLE.STATE_OP
     *
     * @return the value of MESSAGE_TABLE.STATE_OP
     *
     * @mbggenerated
     */
    public Integer getStateOp() {
        return stateOp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE_TABLE.STATE_OP
     *
     * @param stateOp the value for MESSAGE_TABLE.STATE_OP
     *
     * @mbggenerated
     */
    public void setStateOp(Integer stateOp) {
        this.stateOp = stateOp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE_TABLE.TIME_BUILD
     *
     * @return the value of MESSAGE_TABLE.TIME_BUILD
     *
     * @mbggenerated
     */
    public Date getTimeBuild() {
        return timeBuild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE_TABLE.TIME_BUILD
     *
     * @param timeBuild the value for MESSAGE_TABLE.TIME_BUILD
     *
     * @mbggenerated
     */
    public void setTimeBuild(Date timeBuild) {
        this.timeBuild = timeBuild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE_TABLE.COMMENT
     *
     * @return the value of MESSAGE_TABLE.COMMENT
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE_TABLE.COMMENT
     *
     * @param comment the value for MESSAGE_TABLE.COMMENT
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}