package com.cloud.app.model;

import java.util.Date;

public class Share {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARE_TABLE.SHARE_ID
     *
     * @mbggenerated
     */
    private Integer shareId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARE_TABLE.USER_ID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARE_TABLE.MARK
     *
     * @mbggenerated
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARE_TABLE.FILE_NAME
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARE_TABLE.FILE_ID
     *
     * @mbggenerated
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARE_TABLE.SHARE_TIME
     *
     * @mbggenerated
     */
    private Date shareTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHARE_TABLE.COMMENT
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARE_TABLE.SHARE_ID
     *
     * @return the value of SHARE_TABLE.SHARE_ID
     *
     * @mbggenerated
     */
    public Integer getShareId() {
        return shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARE_TABLE.SHARE_ID
     *
     * @param shareId the value for SHARE_TABLE.SHARE_ID
     *
     * @mbggenerated
     */
    public void setShareId(Integer shareId) {
        this.shareId = shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARE_TABLE.USER_ID
     *
     * @return the value of SHARE_TABLE.USER_ID
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARE_TABLE.USER_ID
     *
     * @param userId the value for SHARE_TABLE.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARE_TABLE.MARK
     *
     * @return the value of SHARE_TABLE.MARK
     *
     * @mbggenerated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARE_TABLE.MARK
     *
     * @param mark the value for SHARE_TABLE.MARK
     *
     * @mbggenerated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARE_TABLE.FILE_NAME
     *
     * @return the value of SHARE_TABLE.FILE_NAME
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARE_TABLE.FILE_NAME
     *
     * @param fileName the value for SHARE_TABLE.FILE_NAME
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARE_TABLE.FILE_ID
     *
     * @return the value of SHARE_TABLE.FILE_ID
     *
     * @mbggenerated
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARE_TABLE.FILE_ID
     *
     * @param fileId the value for SHARE_TABLE.FILE_ID
     *
     * @mbggenerated
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARE_TABLE.SHARE_TIME
     *
     * @return the value of SHARE_TABLE.SHARE_TIME
     *
     * @mbggenerated
     */
    public Date getShareTime() {
        return shareTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARE_TABLE.SHARE_TIME
     *
     * @param shareTime the value for SHARE_TABLE.SHARE_TIME
     *
     * @mbggenerated
     */
    public void setShareTime(Date shareTime) {
        this.shareTime = shareTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHARE_TABLE.COMMENT
     *
     * @return the value of SHARE_TABLE.COMMENT
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHARE_TABLE.COMMENT
     *
     * @param comment the value for SHARE_TABLE.COMMENT
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}