package com.cloud.app.model;

import java.util.Date;



public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TABLE.USER_ID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TABLE.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TABLE.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TABLE.BJTU_EMAIL
     *
     * @mbggenerated
     */
    private String bjtuEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TABLE.BJTU_NUMBER
     *
     * @mbggenerated
     */
    private String bjtuNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TABLE.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TABLE.TOTAL_VOLUME
     *
     * @mbggenerated
     */
    private Integer totalVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TABLE.EXISTED_VOLUME
     *
     * @mbggenerated
     */
    private Integer existedVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TABLE.USER_TYPE
     *
     * @mbggenerated
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TABLE.USER_STATE
     *
     * @mbggenerated
     */
    private Integer userState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TABLE.USER_TIME_BUILD
     *
     * @mbggenerated
     */
    private Date userTimeBuild;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TABLE.COMMENT
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TABLE.USER_ID
     *
     * @return the value of USER_TABLE.USER_ID
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TABLE.USER_ID
     *
     * @param userId the value for USER_TABLE.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TABLE.USER_NAME
     *
     * @return the value of USER_TABLE.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TABLE.USER_NAME
     *
     * @param userName the value for USER_TABLE.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TABLE.PASSWORD
     *
     * @return the value of USER_TABLE.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TABLE.PASSWORD
     *
     * @param password the value for USER_TABLE.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TABLE.BJTU_EMAIL
     *
     * @return the value of USER_TABLE.BJTU_EMAIL
     *
     * @mbggenerated
     */
    public String getBjtuEmail() {
        return bjtuEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TABLE.BJTU_EMAIL
     *
     * @param bjtuEmail the value for USER_TABLE.BJTU_EMAIL
     *
     * @mbggenerated
     */
    public void setBjtuEmail(String bjtuEmail) {
        this.bjtuEmail = bjtuEmail == null ? null : bjtuEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TABLE.BJTU_NUMBER
     *
     * @return the value of USER_TABLE.BJTU_NUMBER
     *
     * @mbggenerated
     */
    public String getBjtuNumber() {
        return bjtuNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TABLE.BJTU_NUMBER
     *
     * @param bjtuNumber the value for USER_TABLE.BJTU_NUMBER
     *
     * @mbggenerated
     */
    public void setBjtuNumber(String bjtuNumber) {
        this.bjtuNumber = bjtuNumber == null ? null : bjtuNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TABLE.PHONE
     *
     * @return the value of USER_TABLE.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TABLE.PHONE
     *
     * @param phone the value for USER_TABLE.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TABLE.TOTAL_VOLUME
     *
     * @return the value of USER_TABLE.TOTAL_VOLUME
     *
     * @mbggenerated
     */
    public Integer getTotalVolume() {
        return totalVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TABLE.TOTAL_VOLUME
     *
     * @param totalVolume the value for USER_TABLE.TOTAL_VOLUME
     *
     * @mbggenerated
     */
    public void setTotalVolume(Integer totalVolume) {
        this.totalVolume = totalVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TABLE.EXISTED_VOLUME
     *
     * @return the value of USER_TABLE.EXISTED_VOLUME
     *
     * @mbggenerated
     */
    public Integer getExistedVolume() {
        return existedVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TABLE.EXISTED_VOLUME
     *
     * @param existedVolume the value for USER_TABLE.EXISTED_VOLUME
     *
     * @mbggenerated
     */
    public void setExistedVolume(Integer existedVolume) {
        this.existedVolume = existedVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TABLE.USER_TYPE
     *
     * @return the value of USER_TABLE.USER_TYPE
     *
     * @mbggenerated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TABLE.USER_TYPE
     *
     * @param userType the value for USER_TABLE.USER_TYPE
     *
     * @mbggenerated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TABLE.USER_STATE
     *
     * @return the value of USER_TABLE.USER_STATE
     *
     * @mbggenerated
     */
    public Integer getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TABLE.USER_STATE
     *
     * @param userState the value for USER_TABLE.USER_STATE
     *
     * @mbggenerated
     */
    public void setUserState(Integer userState) {
        this.userState = userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TABLE.USER_TIME_BUILD
     *
     * @return the value of USER_TABLE.USER_TIME_BUILD
     *
     * @mbggenerated
     */
    public Date getUserTimeBuild() {
        return userTimeBuild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TABLE.USER_TIME_BUILD
     *
     * @param userTimeBuild the value for USER_TABLE.USER_TIME_BUILD
     *
     * @mbggenerated
     */
    public void setUserTimeBuild(Date userTimeBuild) {
        this.userTimeBuild = userTimeBuild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TABLE.COMMENT
     *
     * @return the value of USER_TABLE.COMMENT
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TABLE.COMMENT
     *
     * @param comment the value for USER_TABLE.COMMENT
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}