package com.cloud.framwork.dao;

import com.cloud.app.model.GroupAllFile;
import com.cloud.app.model.GroupFile;
import com.cloud.app.model.UserAllFile;

import java.util.List;

public interface GroupFileMapper {
	
	List<GroupAllFile> selectAllByGroupIdAndState(Integer GroupId,int state);
	int myinsert(GroupFile record);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GROUP_FILE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer uploadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GROUP_FILE
     *
     * @mbggenerated
     */
    int insert(GroupFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GROUP_FILE
     *
     * @mbggenerated
     */
    GroupFile selectByPrimaryKey(Integer uploadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GROUP_FILE
     *
     * @mbggenerated
     */
    List<GroupFile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GROUP_FILE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GroupFile record);
}