package com.cloud.framwork.dao;

import com.cloud.app.model.HDFS;
import java.util.List;

public interface HDFSMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HDFS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HDFS
     *
     * @mbggenerated
     */
    int insert(HDFS record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HDFS
     *
     * @mbggenerated
     */
    HDFS selectByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HDFS
     *
     * @mbggenerated
     */
    List<HDFS> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HDFS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HDFS record);
}