package com.cloud.framwork.dao;

import com.cloud.app.model.Member;
import java.util.List;

public interface MemberMapper {
	
	int deleteByGroupIdAndUserId(Integer groupId,Integer userid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_TABLE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer membersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_TABLE
     *
     * @mbggenerated
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_TABLE
     *
     * @mbggenerated
     */
    Member selectByPrimaryKey(Integer membersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_TABLE
     *
     * @mbggenerated
     */
    List<Member> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_TABLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Member record);
}