package com.cloud.framwork.dao;

import com.cloud.app.model.Share;
import java.util.List;

public interface ShareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHARE_TABLE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer shareId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHARE_TABLE
     *
     * @mbggenerated
     */
    int insert(Share record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHARE_TABLE
     *
     * @mbggenerated
     */
    Share selectByPrimaryKey(Integer shareId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHARE_TABLE
     *
     * @mbggenerated
     */
    List<Share> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHARE_TABLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Share record);
}