package com.cloud.framwork.dao;

import com.cloud.app.model.Share;
import com.cloud.app.model.ShareDetail;

import java.util.List;

public interface ShareMapper {
	
	int myinsert(Share record);
	
	List<Share> selectByMark(String mark);
	
	List<Share> selectByUserId(Integer userId);
	
	List<ShareDetail> selectShareDetailByMark(String mark);
	
	  int deleteByMark(String mark);
	  
	  int deleteByUserIdAndFileId(int userid,int fileid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHARE_TABLE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer shareId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHARE_TABLE
     *
     * @mbggenerated
     */
    int insert(Share record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHARE_TABLE
     *
     * @mbggenerated
     */
    Share selectByPrimaryKey(Integer shareId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHARE_TABLE
     *
     * @mbggenerated
     */
    List<Share> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHARE_TABLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Share record);
}