package com.cloud.framwork.dao;

import com.cloud.app.model.Group;
import com.cloud.app.model.User;

import java.util.List;

public interface UserMapper {
	List<User> selectByUserNickName(String userNickName);
	int myinsert(User record);
	 User selectByNameAndPassword(User user);
	 User adminSelectByUserNickname(String userNickname);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TABLE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TABLE
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TABLE
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TABLE
     *
     * @mbggenerated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TABLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);
}