package com.cloud.framwork.dao;

import com.cloud.app.model.UserAllFile;
import com.cloud.app.model.UserFile;

import java.util.List;

public interface UserFileMapper {
	 List<UserAllFile>  selectAllByUserId(Integer userId);
		int myinsert(UserFile record);
		UserFile selectByUserIdAndFileId(Integer userId,Integer fileId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_FILE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer uploadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_FILE
     *
     * @mbggenerated
     */
    int insert(UserFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_FILE
     *
     * @mbggenerated
     */
    UserFile selectByPrimaryKey(Integer uploadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_FILE
     *
     * @mbggenerated
     */
    List<UserFile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_FILE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserFile record);
}